services:
  cvaas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cvaas
    ports:
      - "8000:8000"
    volumes:
      - ./resume.db:/app/resume.db        
      - ./static/uploads:/app/static/uploads 
    restart: unless-stopped
