"""add updated_at fields

Revision ID: 8df764e2b837
Revises: 
Create Date: 2025-05-07 22:45:17.091869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df764e2b837'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('courses', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('education', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('experience', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('info', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('languages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recommendations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('skills', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'updated_at')
    op.drop_column('recommendations', 'updated_at')
    op.drop_column('projects', 'updated_at')
    op.drop_column('languages', 'updated_at')
    op.drop_column('info', 'updated_at')
    op.drop_column('experience', 'updated_at')
    op.drop_column('education', 'updated_at')
    op.drop_column('courses', 'updated_at')
    op.drop_column('certificates', 'updated_at')
    # ### end Alembic commands ###
