"""add 2FA fields to Admin

Revision ID: 69523dc7d905
Revises: 8df764e2b837
Create Date: 2025-05-10 18:09:49.966050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69523dc7d905'
down_revision: Union[str, None] = '8df764e2b837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('totp_secret', sa.String(), nullable=True))
    op.add_column('admin', sa.Column('twofa_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'twofa_enabled')
    op.drop_column('admin', 'totp_secret')
    # ### end Alembic commands ###
