"""add security question and answer to admin

Revision ID: baaaaf0d3ef6
Revises: 69523dc7d905
Create Date: 2025-05-10 18:42:27.446920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baaaaf0d3ef6'
down_revision: Union[str, None] = '69523dc7d905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('security_question', sa.String(), nullable=True))
    op.add_column('admin', sa.Column('security_answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'security_answer')
    op.drop_column('admin', 'security_question')
    # ### end Alembic commands ###
